### ISSUE TITLE
Camera picture gets stuck when activity is not active

### ISSUE THREAD

**Issue by buttairfly** [tuiSSE/carduinodroid-android#4]
if in transceiver mode, and camera picture is displayed, the picture will get stuck if the activity is not active

**Comment by MCBird** [comment]
Should be fixed with commit at 25.02.16 12:13:58 but pls test it on your devices again

https://github.com/tuiSSE/carduinodroid-android/commit/3d6e533454061c9b3310ee1e6124feea37522a04
